### ISSUE TITLE
Сложные трансформации

### ISSUE THREAD

**Issue by arturtr** [baltavay/morphy#1]
Добрый день, Максатбек!

Подскажите возможно ли как-то из глаголов сделать отглагольные существительные,
либо же найти более простые формы слова?

Интересуют такие сценарии:
* окрашивание - красить
* поправить - правка

Насколько понимаю ни в вашей библиотеке ни в pymorphy2 такой возможности нет. 
Но может быть вы подскажете есть ли вообще какие-то алгоритмы позволяющие проводить такие упрощения слов?

**Comment by baltavay** [comment]
Здравствуйте, Артур! 
К сожалению такой возможности нет. Это из-за того, что в словаре opencorpora нет таких связей между словами. Вряд ли есть алгоритмы, которые могут так упрощать. 
Чтобы это сделать нужны словари, где будут эти связи. И тогда можно будет сделать то, что вы хотите.

**Comment by arturtr** [comment]
Добрый день, Максатбек!

Благодарю за столь быстрый ответ. Известно ли вам о наличии таких словарей в публичном доступе? Либо с возможностью их приобрести.

Пока только один нашли http://stemmings.ru/
Приходится парсить данные с сайта. Но это лучше чем ничего :)

**Comment by baltavay** [comment]
День добрый, Артур! 

Мне не известно о наличии таких словарей.

**Comment by arturtr** [comment]
Спасибо за информацию
